// Generated by Haxe 4.3.7
(function ($global) {
	"use strict";
	var $estr = function () {
			return js_Boot.__string_rec(this, "");
		},
		$hxEnums = $hxEnums || {},
		$_;
	var EReg = function (r, opt) {
		this.r = new RegExp(r, opt.split("u").join(""));
	};
	EReg.__name__ = true;
	EReg.prototype = {
		match: function (s) {
			if (this.r.global) {
				this.r.lastIndex = 0;
			}
			this.r.m = this.r.exec(s);
			this.r.s = s;
			return this.r.m != null;
		},
	};
	Math.__name__ = true;
	var Reflect = function () {};
	Reflect.__name__ = true;
	Reflect.field = function (o, field) {
		try {
			return o[field];
		} catch (_g) {
			return null;
		}
	};
	var Std = function () {};
	Std.__name__ = true;
	Std.string = function (s) {
		return js_Boot.__string_rec(s, "");
	};
	var forge_data_SynergyTier = ($hxEnums["forge.data.SynergyTier"] = {
		__ename__: true,
		__constructs__: null,
		Core: {
			_hx_name: "Core",
			_hx_index: 0,
			__enum__: "forge.data.SynergyTier",
			toString: $estr,
		},
		Good: {
			_hx_name: "Good",
			_hx_index: 1,
			__enum__: "forge.data.SynergyTier",
			toString: $estr,
		},
		Situational: {
			_hx_name: "Situational",
			_hx_index: 2,
			__enum__: "forge.data.SynergyTier",
			toString: $estr,
		},
		Weak: {
			_hx_name: "Weak",
			_hx_index: 3,
			__enum__: "forge.data.SynergyTier",
			toString: $estr,
		},
		Trap: {
			_hx_name: "Trap",
			_hx_index: 4,
			__enum__: "forge.data.SynergyTier",
			toString: $estr,
		},
	});
	forge_data_SynergyTier.__constructs__ = [
		forge_data_SynergyTier.Core,
		forge_data_SynergyTier.Good,
		forge_data_SynergyTier.Situational,
		forge_data_SynergyTier.Weak,
		forge_data_SynergyTier.Trap,
	];
	var forge_rules_DamageType = ($hxEnums["forge.rules.DamageType"] = {
		__ename__: true,
		__constructs__: null,
		Physical: {
			_hx_name: "Physical",
			_hx_index: 0,
			__enum__: "forge.rules.DamageType",
			toString: $estr,
		},
		Magic: {
			_hx_name: "Magic",
			_hx_index: 1,
			__enum__: "forge.rules.DamageType",
			toString: $estr,
		},
		Hybrid: {
			_hx_name: "Hybrid",
			_hx_index: 2,
			__enum__: "forge.rules.DamageType",
			toString: $estr,
		},
	});
	forge_rules_DamageType.__constructs__ = [
		forge_rules_DamageType.Physical,
		forge_rules_DamageType.Magic,
		forge_rules_DamageType.Hybrid,
	];
	var forge_rules_ItemClassifier = function () {};
	forge_rules_ItemClassifier.__name__ = true;
	forge_rules_ItemClassifier.classify = function (id, item) {
		var desc =
			item.description != null ? item.description.toLowerCase() : "";
		var stats = item.stats != null ? item.stats : {};
		var tags = item.tags != null ? item.tags : [];
		var cost = item.gold != null ? item.gold.total : 0;
		var depth = item.depth != null ? item.depth : 1;
		var isBoots = tags.indexOf("Boots") >= 0;
		var isTrinket = tags.indexOf("Trinket") >= 0 || cost == 0;
		var isOrnn = item.requiredAlly != null && item.requiredAlly == "Ornn";
		var isSupportItem =
			tags.indexOf("Support") >= 0 ||
			tags.indexOf("GoldPer") >= 0 ||
			desc.indexOf("ally") >= 0 ||
			desc.indexOf("allies") >= 0;
		var isComponent = item.into != null && item.into.length > 0;
		var isBasic = depth <= 1 && isComponent;
		var isEpic = depth == 2;
		var isLegendary = depth >= 3 && !isSupportItem;
		var isMythic = desc.indexOf("mythic passive") >= 0;
		var apVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatMagicDamageMod",
		);
		var adVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatPhysicalDamageMod",
		);
		var asVal = forge_rules_ItemClassifier.statVal(
			stats,
			"PercentAttackSpeedMod",
		);
		var armorVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatArmorMod",
		);
		var mrVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatSpellBlockMod",
		);
		var hpVal = forge_rules_ItemClassifier.statVal(stats, "FlatHPPoolMod");
		var manaVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatMPPoolMod",
		);
		var hpRegenVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatHPRegenMod",
		);
		var manaRegenVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatMPRegenMod",
		);
		var critVal = forge_rules_ItemClassifier.statVal(
			stats,
			"FlatCritChanceMod",
		);
		var msVal =
			forge_rules_ItemClassifier.statVal(stats, "FlatMovementSpeedMod") +
			forge_rules_ItemClassifier.statVal(
				stats,
				"PercentMovementSpeedMod",
			);
		var givesLethality = desc.indexOf("lethality") >= 0;
		var givesArmorPen =
			desc.indexOf("armor penetration") >= 0 ||
			desc.indexOf("% armor") >= 0;
		var givesMagicPen =
			desc.indexOf("magic penetration") >= 0 ||
			desc.indexOf("% magic") >= 0 ||
			desc.indexOf("void staff") >= 0;
		var givesLifesteal =
			desc.indexOf("life steal") >= 0 || desc.indexOf("lifesteal") >= 0;
		var givesOmnivamp = desc.indexOf("omnivamp") >= 0;
		var givesAh = desc.indexOf("ability haste") >= 0;
		return {
			id: id,
			name: item.name,
			cost: cost,
			tags: tags,
			givesAp: apVal > 0,
			givesAd: adVal > 0,
			givesAs: asVal > 0,
			givesArmor: armorVal > 0,
			givesMr: mrVal > 0,
			givesHp: hpVal > 0,
			givesMana: manaVal > 0 || desc.indexOf("mana") >= 0,
			givesHpRegen: hpRegenVal > 0 || desc.indexOf("health regen") >= 0,
			givesManaRegen: manaRegenVal > 0,
			givesLethality: givesLethality,
			givesArmorPen: givesArmorPen,
			givesMagicPen: givesMagicPen,
			givesLifesteal: givesLifesteal,
			givesOmnivamp: givesOmnivamp,
			givesCrit: critVal > 0,
			givesMs: msVal > 0,
			givesAh: givesAh,
			hasOnHitPassive: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.ON_HIT_KW,
			),
			hasShieldPassive: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.SHIELD_KW,
			),
			hasHealPassive: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.HEAL_KW,
			),
			hasAllyHealPassive: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.ALLY_HEAL_KW,
			),
			hasExecutePassive: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.EXECUTE_KW,
			),
			hasDoTPassive: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.DOT_KW,
			),
			hasDashPassive: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.DASH_KW,
			),
			hasSpellblade: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.SPELLBLADE_KW,
			),
			hasSheen: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.SHEEN_KW,
			),
			hasAntiHeal:
				desc.indexOf("grievous wounds") >= 0 ||
				desc.indexOf("healing reduction") >= 0,
			hasAoeDmg: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.AOE_KW,
			),
			hasManagate: forge_rules_ItemClassifier.containsAny(
				desc,
				forge_rules_ItemClassifier.MANAGATE_KW,
			),
			hasMinionExec:
				desc.indexOf("cannon minion") >= 0 ||
				desc.indexOf("last hit") >= 0,
			isLegendary: isLegendary,
			isEpic: isEpic,
			isBasic: isBasic,
			isMythic: isMythic,
			isBoots: isBoots,
			isTrinket: isTrinket,
			isOrnn: isOrnn,
			isSupportItem: isSupportItem,
			isComponent: isComponent,
			pickRate: item.pickRate != null ? item.pickRate : 0.0,
		};
	};
	forge_rules_ItemClassifier.statVal = function (stats, key) {
		var v = Reflect.field(stats, key);
		if (v == null) {
			return 0.0;
		}
		return v;
	};
	forge_rules_ItemClassifier.containsAny = function (text, keywords) {
		var _g = 0;
		while (_g < keywords.length) {
			var kw = keywords[_g];
			++_g;
			if (text.indexOf(kw) >= 0) {
				return true;
			}
		}
		return false;
	};
	var forge_rules_ProfileBuilder = function () {};
	forge_rules_ProfileBuilder.__name__ = true;
	forge_rules_ProfileBuilder.build = function (champion) {
		var abilityData =
			forge_rules_ProfileBuilder.analyzeChampionAbilities(champion);
		var resource = forge_rules_ProfileBuilder.detectResource(
			champion.partype,
		);
		var attackRange = champion.stats.attackrange;
		var range =
			attackRange <= 200 ? forge_rules_RangeType.Melee
			: attackRange < 500 ? forge_rules_RangeType.Short
			: forge_rules_RangeType.Ranged;
		var hasAp =
			abilityData.apScaledAbilities.length > 0 ||
			champion.info.magic >= 6;
		var hasAd =
			abilityData.adScaledAbilities.length > 0 ||
			champion.info.attack >= 6;
		var primaryDmg = forge_rules_ProfileBuilder.detectPrimaryDamage(
			champion,
			hasAp,
			hasAd,
		);
		var isHighAs = champion.stats.attackspeed > 0.65;
		var autoAttackPriority =
			champion.tags.indexOf("Marksman") >= 0 ? 1.0
			: (
				abilityData.hasAutoResets ||
				abilityData.onHitAbilities.length > 0
			) ?
				0.85
			: (
				champion.tags.indexOf("Fighter") >= 0 ||
				champion.tags.indexOf("Assassin") >= 0
			) ?
				0.7
			: champion.tags.indexOf("Tank") >= 0 ? 0.45
			: champion.tags.indexOf("Mage") >= 0 ? 0.25
			: champion.tags.indexOf("Support") >= 0 ? 0.2
			: 0.35;
		return {
			id: champion.id,
			name: champion.name,
			tags: champion.tags,
			resource: resource,
			range: range,
			attackRange: attackRange,
			primaryDamage: primaryDmg,
			hasApScaling: hasAp,
			hasAdScaling: hasAd,
			apScaledAbilities: abilityData.apScaledAbilities,
			adScaledAbilities: abilityData.adScaledAbilities,
			autoAttackPriority: autoAttackPriority,
			hasOnHit: abilityData.onHitAbilities.length > 0,
			onHitAbilities: abilityData.onHitAbilities,
			hasOnAttack: abilityData.onAttackAbilities.length > 0,
			onAttackAbilities: abilityData.onAttackAbilities,
			hasOnSpellHit: abilityData.onSpellHitAbilities.length > 0,
			onSpellHitAbilities: abilityData.onSpellHitAbilities,
			hasAutoResets: abilityData.hasAutoResets,
			hasDoT: abilityData.hasDoT,
			hasDash: abilityData.hasDash,
			hasShield: abilityData.hasShield,
			hasSelfShield: abilityData.hasSelfShield,
			hasHeal: abilityData.hasHeal,
			hasSelfHeal: abilityData.hasSelfHeal,
			hasCc: abilityData.hasCc,
			hasSlow: abilityData.hasSlow,
			hasStun: abilityData.hasStun,
			hasKnockup: abilityData.hasKnockup,
			hasSilence: abilityData.hasSilence,
			hasExecute: abilityData.hasExecute,
			hasStealth: abilityData.hasStealth,
			hasGlobalUlt: forge_rules_ProfileBuilder.detectGlobalUlt(champion),
			hasPermaSlowOrSnare: abilityData.hasSlow || abilityData.hasCc,
			defenseRating: champion.info.defense,
			attackRating: champion.info.attack,
			magicRating: champion.info.magic,
			isHighAttackSpeed: isHighAs,
			isLowBaseAd: champion.stats.attackdamage < 52,
			isManaless:
				resource == forge_rules_ResourceType.Manaless ||
				resource == forge_rules_ResourceType.Energy,
			isLowMana:
				resource == forge_rules_ResourceType.Mana &&
				champion.stats.mp < 300,
			isHighMana:
				resource == forge_rules_ResourceType.Mana &&
				champion.stats.mp >= 400,
			isMarksman: champion.tags.indexOf("Marksman") >= 0,
			isMage: champion.tags.indexOf("Mage") >= 0,
			isSupport: champion.tags.indexOf("Support") >= 0,
			isAssassin: champion.tags.indexOf("Assassin") >= 0,
			isTank: champion.tags.indexOf("Tank") >= 0,
			isFighter: champion.tags.indexOf("Fighter") >= 0,
		};
	};
	forge_rules_ProfileBuilder.analyzeChampionAbilities = function (c) {
		var apScaledAbilities = [];
		var adScaledAbilities = [];
		var onHitAbilities = [];
		var onAttackAbilities = [];
		var onSpellHitAbilities = [];
		var hasAutoResets = false;
		var hasDoT = false;
		var hasDash = false;
		var hasShield = false;
		var hasSelfShield = false;
		var hasHeal = false;
		var hasSelfHeal = false;
		var hasCc = false;
		var hasSlow = false;
		var hasStun = false;
		var hasKnockup = false;
		var hasSilence = false;
		var hasExecute = false;
		var hasStealth = false;
		var _g = 0;
		var _g1 = c.spells;
		while (_g < _g1.length) {
			var spell = _g1[_g];
			++_g;
			var text = (
				spell.name +
				" " +
				(spell.description != null ? spell.description : "") +
				" " +
				(spell.tooltip != null ? spell.tooltip : "")
			).toLowerCase();
			if (forge_rules_ProfileBuilder.isSpellApScaled(spell)) {
				apScaledAbilities.push(spell.name);
			}
			if (forge_rules_ProfileBuilder.isSpellAdScaled(spell)) {
				adScaledAbilities.push(spell.name);
			}
			if (forge_rules_ProfileBuilder.isSpellOnHit(text)) {
				onHitAbilities.push(spell.name);
			}
			if (forge_rules_ProfileBuilder.isSpellOnAttack(text)) {
				onAttackAbilities.push(spell.name);
			}
			if (forge_rules_ProfileBuilder.isSpellOnSpellHit(text)) {
				onSpellHitAbilities.push(spell.name);
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.AUTO_RESET_KEYWORDS,
				)
			) {
				hasAutoResets = true;
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.DOT_KEYWORDS,
				)
			) {
				hasDoT = true;
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.DASH_KEYWORDS,
				)
			) {
				hasDash = true;
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.SHIELD_KEYWORDS,
				)
			) {
				hasShield = true;
				if (
					forge_rules_ProfileBuilder.containsAny(
						text,
						["self", "yourself", "you"],
						true,
					)
				) {
					hasSelfShield = true;
				}
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.HEAL_KEYWORDS,
				)
			) {
				hasHeal = true;
				if (
					forge_rules_ProfileBuilder.containsAny(
						text,
						["self", "yourself", "you"],
						true,
					) ||
					text.indexOf("regain") >= 0
				) {
					hasSelfHeal = true;
				}
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.CC_KEYWORDS,
				)
			) {
				hasCc = true;
			}
			if (text.indexOf("slow") >= 0) {
				hasSlow = true;
			}
			if (text.indexOf("stun") >= 0 || text.indexOf("root") >= 0) {
				hasStun = true;
			}
			if (text.indexOf("knock") >= 0 || text.indexOf("airborne") >= 0) {
				hasKnockup = true;
			}
			if (text.indexOf("silence") >= 0) {
				hasSilence = true;
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.EXECUTE_KEYWORDS,
				)
			) {
				hasExecute = true;
			}
			if (
				forge_rules_ProfileBuilder.containsAny(
					text,
					forge_rules_ProfileBuilder.STEALTH_KEYWORDS,
				)
			) {
				hasStealth = true;
			}
		}
		return {
			apScaledAbilities: apScaledAbilities,
			adScaledAbilities: adScaledAbilities,
			onHitAbilities: onHitAbilities,
			onAttackAbilities: onAttackAbilities,
			onSpellHitAbilities: onSpellHitAbilities,
			hasAutoResets: hasAutoResets,
			hasDoT: hasDoT,
			hasDash: hasDash,
			hasShield: hasShield,
			hasHeal: hasHeal,
			hasCc: hasCc,
			hasSlow: hasSlow,
			hasStun: hasStun,
			hasKnockup: hasKnockup,
			hasSilence: hasSilence,
			hasExecute: hasExecute,
			hasStealth: hasStealth,
		};
	};
	forge_rules_ProfileBuilder.isSpellApScaled = function (spell) {
		if (spell.vars != null) {
			var _g = 0;
			var _g1 = spell.vars;
			while (_g < _g1.length) {
				var v = _g1[_g];
				++_g;
				var key = Reflect.field(v, "link");
				if (key != null && key.toLowerCase() == "ap") {
					return true;
				}
			}
		}
		return false;
	};
	forge_rules_ProfileBuilder.isSpellAdScaled = function (spell) {
		if (spell.vars != null) {
			var _g = 0;
			var _g1 = spell.vars;
			while (_g < _g1.length) {
				var v = _g1[_g];
				++_g;
				var key = Reflect.field(v, "link");
				if (
					key != null &&
					(key.toLowerCase() == "ad" ||
						key.toLowerCase() == "attackdamage")
				) {
					return true;
				}
			}
		}
		return false;
	};
	forge_rules_ProfileBuilder.isSpellOnHit = function (text) {
		return forge_rules_ProfileBuilder.containsAny(
			text,
			["on-hit", "on hit", "attacks deal", "applies on-hit"],
			false,
		);
	};
	forge_rules_ProfileBuilder.isSpellOnAttack = function (text) {
		return forge_rules_ProfileBuilder.containsAny(
			text,
			["auto attack", "basic attack", "attack speed", "when you attack"],
			false,
		);
	};
	forge_rules_ProfileBuilder.isSpellOnSpellHit = function (text) {
		return forge_rules_ProfileBuilder.containsAny(text, [
			"on spell hit",
			"spell hit",
			"when you hit with a spell",
			"on hit by spell",
		]);
	};
	forge_rules_ProfileBuilder.collectAbilityText = function (c) {
		var parts = [];
		if (c.passive != null) {
			parts.push(c.passive.name);
			parts.push(c.passive.description);
		}
		var _g = 0;
		var _g1 = c.spells;
		while (_g < _g1.length) {
			var spell = _g1[_g];
			++_g;
			parts.push(spell.name);
			parts.push(spell.description);
			parts.push(spell.tooltip);
		}
		return parts.join(" ");
	};
	forge_rules_ProfileBuilder.detectResource = function (partype) {
		switch (partype.toLowerCase()) {
			case "":
			case "no cost":
			case "none":
				return forge_rules_ResourceType.Manaless;
			case "energy":
				return forge_rules_ResourceType.Energy;
			case "mana":
				return forge_rules_ResourceType.Mana;
			default:
				return forge_rules_ResourceType.Manaless;
		}
	};
	forge_rules_ProfileBuilder.detectPrimaryDamage = function (
		c,
		hasAp,
		hasAd,
	) {
		if (hasAp && hasAd) {
			return forge_rules_DamageType.Hybrid;
		}
		if (hasAp) {
			return forge_rules_DamageType.Magic;
		}
		if (c.info.magic > c.info.attack + 2) {
			return forge_rules_DamageType.Magic;
		}
		return forge_rules_DamageType.Physical;
	};
	forge_rules_ProfileBuilder.detectGlobalUlt = function (c) {
		if (c.spells.length < 4) {
			return false;
		}
		var ult = c.spells[3];
		var lower = (ult.description + " " + ult.tooltip).toLowerCase();
		if (lower.indexOf("global") < 0) {
			return lower.indexOf("anywhere on") >= 0;
		} else {
			return true;
		}
	};
	forge_rules_ProfileBuilder.containsAny = function (
		text,
		keywords,
		wholeWords,
	) {
		if (wholeWords == null) {
			wholeWords = false;
		}
		var lower = text.toLowerCase();
		var _g = 0;
		while (_g < keywords.length) {
			var kw = keywords[_g];
			++_g;
			var k = kw.toLowerCase();
			if (!wholeWords) {
				if (lower.indexOf(k) >= 0) {
					return true;
				}
			} else {
				var rx = new EReg("\\b" + k + "\\b", "i");
				if (rx.match(text)) {
					return true;
				}
			}
		}
		return false;
	};
	var forge_rules_RangeType = ($hxEnums["forge.rules.RangeType"] = {
		__ename__: true,
		__constructs__: null,
		Melee: {
			_hx_name: "Melee",
			_hx_index: 0,
			__enum__: "forge.rules.RangeType",
			toString: $estr,
		},
		Short: {
			_hx_name: "Short",
			_hx_index: 1,
			__enum__: "forge.rules.RangeType",
			toString: $estr,
		},
		Ranged: {
			_hx_name: "Ranged",
			_hx_index: 2,
			__enum__: "forge.rules.RangeType",
			toString: $estr,
		},
	});
	forge_rules_RangeType.__constructs__ = [
		forge_rules_RangeType.Melee,
		forge_rules_RangeType.Short,
		forge_rules_RangeType.Ranged,
	];
	var forge_rules_ResourceType = ($hxEnums["forge.rules.ResourceType"] = {
		__ename__: true,
		__constructs__: null,
		Mana: {
			_hx_name: "Mana",
			_hx_index: 0,
			__enum__: "forge.rules.ResourceType",
			toString: $estr,
		},
		Energy: {
			_hx_name: "Energy",
			_hx_index: 1,
			__enum__: "forge.rules.ResourceType",
			toString: $estr,
		},
		Manaless: {
			_hx_name: "Manaless",
			_hx_index: 2,
			__enum__: "forge.rules.ResourceType",
			toString: $estr,
		},
	});
	forge_rules_ResourceType.__constructs__ = [
		forge_rules_ResourceType.Mana,
		forge_rules_ResourceType.Energy,
		forge_rules_ResourceType.Manaless,
	];
	var forge_rules_SynergyEngine = function () {};
	forge_rules_SynergyEngine.__name__ = true;
	forge_rules_SynergyEngine.score = function (champ, item) {
		var s = 5;
		var reasons = [];
		if (item.hasManagate && champ.isManaless) {
			s -= 5;
			reasons.push({
				r: "Mana-scaling item on a manaless champion",
				delta: -5,
			});
		}
		if (item.givesMana && champ.isManaless) {
			s -= 2;
			reasons.push({
				r: "Mana stat wasted on manaless champion",
				delta: -2,
			});
		}
		if (item.givesManaRegen && champ.isManaless) {
			--s;
			reasons.push({ r: "Mana regen wasted", delta: -1 });
		}
		if (item.hasSpellblade && champ.isManaless) {
			--s;
			reasons.push({
				r: "Spellblade passive requires resource management",
				delta: -1,
			});
		}
		if (item.givesAp && !champ.hasApScaling) {
			s -= 6;
			reasons.push({
				r: "AP stat wasted — no ability power scaling",
				delta: -6,
			});
		}
		if (item.givesAd && !champ.hasAdScaling) {
			var allowsAdDespiteNoScaling =
				champ.hasOnHit ||
				champ.hasOnAttack ||
				champ.hasAutoResets ||
				champ.isMarksman ||
				champ.isHighAttackSpeed ||
				(champ.name != null &&
					(champ.name.toLowerCase() == "teemo" ||
						champ.name.toLowerCase() == "lulu"));
			if (!allowsAdDespiteNoScaling) {
				s -= 6;
				reasons.push({
					r: "AD stat wasted — no AD scaling",
					delta: -6,
				});
			} else {
				--s;
				reasons.push({
					r: "AD item is situational for this champion (off-meta)",
					delta: -1,
				});
			}
		}
		if (item.givesAp && !champ.hasApScaling && !champ.isMage) {
			s -= 3;
			reasons.push({
				r: "AP stat wasted — no ability power scaling",
				delta: -3,
			});
		}
		if (item.givesAp && champ.hasApScaling) {
			s += 2;
			reasons.push({ r: "Boosts AP scaling abilities", delta: 2 });
		}
		if (item.givesMagicPen && !champ.hasApScaling) {
			s -= 3;
			reasons.push({
				r: "Magic penetration wasted — no magic damage",
				delta: -3,
			});
		}
		if (item.givesMagicPen && champ.hasApScaling) {
			s += 2;
			reasons.push({ r: "Magic pen amplifies AP damage", delta: 2 });
		}
		if (
			item.givesAd &&
			champ.primaryDamage == forge_rules_DamageType.Magic &&
			!champ.hasAdScaling
		) {
			s -= 2;
			reasons.push({
				r: "AD stat underutilized on AP champion",
				delta: -2,
			});
		}
		if (
			item.givesAd &&
			(champ.hasAdScaling ||
				champ.primaryDamage == forge_rules_DamageType.Physical)
		) {
			++s;
			reasons.push({ r: "AD scales abilities and autos", delta: 1 });
		}
		if (
			item.givesLethality &&
			champ.primaryDamage == forge_rules_DamageType.Magic
		) {
			s -= 3;
			reasons.push({
				r: "Lethality wasted — deals magic damage",
				delta: -3,
			});
		}
		if (
			item.givesLethality &&
			champ.primaryDamage == forge_rules_DamageType.Physical &&
			champ.isAssassin
		) {
			s += 3;
			reasons.push({
				r: "Lethality on assassination-focused kit",
				delta: 3,
			});
		}
		if (
			item.givesLethality &&
			champ.primaryDamage == forge_rules_DamageType.Physical &&
			!champ.isAssassin
		) {
			++s;
			reasons.push({ r: "Lethality helps physical damage", delta: 1 });
		}
		if (
			item.givesArmorPen &&
			champ.primaryDamage == forge_rules_DamageType.Magic
		) {
			s -= 3;
			reasons.push({
				r: "Armor penetration wasted — magic damage",
				delta: -3,
			});
		}
		if (
			item.givesArmorPen &&
			champ.primaryDamage == forge_rules_DamageType.Physical
		) {
			s += 2;
			reasons.push({
				r: "Armor penetration amplifies physical damage",
				delta: 2,
			});
		}
		if (
			item.givesAs &&
			!champ.hasOnHit &&
			champ.primaryDamage == forge_rules_DamageType.Magic
		) {
			s -= 2;
			reasons.push({
				r: "Attack speed wasted — ability-focused champion",
				delta: -2,
			});
		}
		if (item.givesAs && (champ.hasOnHit || champ.isMarksman)) {
			s += 2;
			reasons.push({
				r: "Attack speed enhances on-hit or auto attacks",
				delta: 2,
			});
		}
		if (item.givesAs && champ.isHighAttackSpeed) {
			++s;
			reasons.push({
				r: "Stacks with naturally high attack speed",
				delta: 1,
			});
		}
		if (
			item.hasOnHitPassive &&
			!champ.hasOnHit &&
			champ.primaryDamage == forge_rules_DamageType.Magic
		) {
			s -= 2;
			reasons.push({
				r: "On-hit effect wasted — champion doesn't auto-attack repeatedly",
				delta: -2,
			});
		}
		if (
			item.hasOnHitPassive &&
			(champ.hasOnHit || champ.isMarksman || champ.isFighter)
		) {
			s += 2;
			reasons.push({
				r: "On-hit passive procs frequently with kit",
				delta: 2,
			});
		}
		if (item.hasOnHitPassive && champ.hasAutoResets) {
			++s;
			reasons.push({
				r: "Extra value with auto-reset abilities",
				delta: 1,
			});
		}
		if (
			item.givesCrit &&
			!champ.isMarksman &&
			champ.primaryDamage == forge_rules_DamageType.Magic
		) {
			s -= 3;
			reasons.push({
				r: "Crit wasted on non-crit, non-AD champion",
				delta: -3,
			});
		}
		if (
			item.givesCrit &&
			(champ.isMarksman ||
				(champ.primaryDamage == forge_rules_DamageType.Physical &&
					champ.attackRating >= 6))
		) {
			s += 2;
			reasons.push({
				r: "Crit scales with auto-attack playstyle",
				delta: 2,
			});
		}
		if (item.isSupportItem && !champ.isSupport) {
			s -= 4;
			reasons.push({
				r: "Support item for non-support champion",
				delta: -4,
			});
		}
		if (item.isSupportItem && champ.isSupport) {
			s += 3;
			reasons.push({
				r: "Support item is appropriate for support champion",
				delta: 3,
			});
		}
		if (champ.autoAttackPriority >= 0.8 && item.givesAs) {
			s += 2;
			reasons.push({
				r: "High auto-attack champion benefits attack speed",
				delta: 2,
			});
		}
		if (champ.autoAttackPriority >= 0.8 && item.hasOnHitPassive) {
			s += 2;
			reasons.push({
				r: "High auto-attack champion can use on-hit effects well",
				delta: 2,
			});
		}
		if (champ.autoAttackPriority < 0.4 && item.hasOnHitPassive) {
			--s;
			reasons.push({
				r: "Low auto-attack champion gets little value from on-hit items",
				delta: -1,
			});
		}
		if (item.pickRate > 10) {
			++s;
			reasons.push({ r: "High pick-rate item (popular)", delta: 1 });
		}
		if (item.pickRate >= 20 && champ.isAssassin) {
			++s;
			reasons.push({ r: "Common for assassins in meta", delta: 1 });
		}
		if (
			item.pickRate > 15 &&
			item.isSupportItem &&
			(champ.isMage || champ.isAssassin)
		) {
			--s;
			reasons.push({
				r: "Popular support item may not fit non-support champion",
				delta: -1,
			});
		}
		if (
			item.hasSheen &&
			!champ.hasAutoResets &&
			champ.primaryDamage == forge_rules_DamageType.Magic
		) {
			--s;
			reasons.push({
				r: "Sheen proc requires auto-attacking after spells",
				delta: -1,
			});
		}
		if (item.hasSheen && champ.hasAutoResets) {
			s += 2;
			reasons.push({
				r: "Sheen/Spellblade synergizes with auto-reset kit",
				delta: 2,
			});
		}
		if (
			item.hasSheen &&
			champ.isFighter &&
			champ.primaryDamage == forge_rules_DamageType.Physical
		) {
			s += 2;
			reasons.push({
				r: "Sheen proc adds strong burst to melee fighter",
				delta: 2,
			});
		}
		if (item.hasSheen && champ.isMage && !champ.hasAutoResets) {
			--s;
			reasons.push({
				r: "Mage often can't reset autos to proc Sheen reliably",
				delta: -1,
			});
		}
		if (
			item.givesMana &&
			champ.resource == forge_rules_ResourceType.Mana &&
			champ.isHighMana
		) {
			++s;
			reasons.push({ r: "Benefits from higher mana pool", delta: 1 });
		}
		if (
			item.givesMana &&
			champ.resource == forge_rules_ResourceType.Mana &&
			champ.isMage
		) {
			++s;
			reasons.push({ r: "Mages appreciate sustained mana", delta: 1 });
		}
		if (
			item.hasManagate &&
			champ.resource == forge_rules_ResourceType.Mana &&
			champ.isHighMana
		) {
			s += 2;
			reasons.push({
				r: "Mana-scaling passive benefits from large mana pool",
				delta: 2,
			});
		}
		if (
			item.givesManaRegen &&
			champ.resource == forge_rules_ResourceType.Mana
		) {
			++s;
			reasons.push({ r: "Mana regen sustains spell casting", delta: 1 });
		}
		if (
			item.givesManaRegen &&
			champ.resource == forge_rules_ResourceType.Energy
		) {
			--s;
			reasons.push({
				r: "Mana regen wasted on Energy champion",
				delta: -1,
			});
		}
		if (item.givesArmor && champ.defenseRating >= 5) {
			++s;
			reasons.push({ r: "Armor fits tanky playstyle", delta: 1 });
		}
		if (item.givesMr && champ.defenseRating >= 5) {
			++s;
			reasons.push({ r: "MR fits tanky playstyle", delta: 1 });
		}
		if (item.givesHp && champ.defenseRating >= 6) {
			++s;
			reasons.push({ r: "HP suits durable frontline role", delta: 1 });
		}
		if ((item.givesArmor || item.givesMr || item.givesHp) && champ.isTank) {
			s += 2;
			reasons.push({
				r: "Defensive stats core on tank champion",
				delta: 2,
			});
		}
		if (item.givesArmor && champ.isAssassin) {
			--s;
			reasons.push({
				r: "Armor reduces burst effectiveness for assassin",
				delta: -1,
			});
		}
		if (item.givesMr && champ.isAssassin) {
			--s;
			reasons.push({
				r: "MR reduces burst effectiveness for assassin",
				delta: -1,
			});
		}
		if (item.givesMs && champ.hasDash) {
			++s;
			reasons.push({
				r: "Movement speed enhances dash/mobility kit",
				delta: 1,
			});
		}
		if (item.hasDashPassive && champ.isAssassin) {
			s += 2;
			reasons.push({
				r: "Active dash useful for assassination / reposition",
				delta: 2,
			});
		}
		if (item.hasDashPassive && champ.isTank) {
			--s;
			reasons.push({
				r: "Dash active less valuable on slow frontline",
				delta: -1,
			});
		}
		if (
			item.givesLifesteal &&
			champ.primaryDamage == forge_rules_DamageType.Magic
		) {
			s -= 2;
			reasons.push({
				r: "Lifesteal only works with physical auto attacks",
				delta: -2,
			});
		}
		if (
			item.givesLifesteal &&
			(champ.isMarksman ||
				(champ.attackRating >= 6 &&
					champ.primaryDamage == forge_rules_DamageType.Physical))
		) {
			s += 2;
			reasons.push({
				r: "Lifesteal provides strong sustain with frequent autos",
				delta: 2,
			});
		}
		if (item.givesOmnivamp && champ.hasDoT) {
			++s;
			reasons.push({
				r: "Omnivamp applies to all damage sources including DoT",
				delta: 1,
			});
		}
		if (item.givesOmnivamp && champ.hasApScaling) {
			++s;
			reasons.push({
				r: "Omnivamp sustains through spell damage",
				delta: 1,
			});
		}
		if (
			Object.prototype.hasOwnProperty.call(item, "hasAllyHealPassive") &&
			item.hasAllyHealPassive
		) {
			var canHealAllies = champ.hasHeal && !champ.hasSelfHeal;
			if (!canHealAllies) {
				s -= 3;
				reasons.push({
					r: "Support active requires healing allies — champion can't heal allies",
					delta: -3,
				});
			} else {
				s += 2;
				reasons.push({
					r: "Can trigger ally-heal support active",
					delta: 2,
				});
			}
		}
		if (item.hasShieldPassive && champ.hasShield) {
			++s;
			reasons.push({
				r: "Stacks with champion's own shielding",
				delta: 1,
			});
		}
		if (item.hasShieldPassive && champ.isTank) {
			++s;
			reasons.push({
				r: "Shield passive suits frontline survivability",
				delta: 1,
			});
		}
		if (
			item.givesAh &&
			champ.resource == forge_rules_ResourceType.Mana &&
			champ.isMage
		) {
			++s;
			reasons.push({
				r: "Ability haste allows more frequent spell casting",
				delta: 1,
			});
		}
		if (item.givesAh && champ.hasCc) {
			++s;
			reasons.push({ r: "More haste = more CC uptime", delta: 1 });
		}
		if (item.givesAh && champ.isFighter) {
			++s;
			reasons.push({
				r: "Ability haste improves sustained fighter damage",
				delta: 1,
			});
		}
		if (item.hasExecutePassive && champ.hasExecute) {
			s += 2;
			reasons.push({
				r: "Stacks with champion's own execute mechanic",
				delta: 2,
			});
		}
		if (item.hasExecutePassive && champ.isAssassin) {
			++s;
			reasons.push({
				r: "Execute helps secure kills for assassin",
				delta: 1,
			});
		}
		if (item.hasDoTPassive && champ.hasDoT) {
			++s;
			reasons.push({
				r: "DoT passive complements champion's damage-over-time",
				delta: 1,
			});
		}
		if (champ.isMarksman) {
			if (
				item.givesCrit ||
				item.givesAs ||
				item.givesAd ||
				item.givesLifesteal
			) {
				++s;
				reasons.push({ r: "Core marksman stats", delta: 1 });
			}
			if (item.givesArmor || item.givesMr || item.givesHp) {
				--s;
				reasons.push({
					r: "Defensive stats suboptimal on marksman",
					delta: -1,
				});
			}
		}
		if (champ.isMage) {
			if (item.givesAp || item.givesMagicPen || item.givesAh) {
				++s;
				reasons.push({ r: "Core mage stats", delta: 1 });
			}
		}
		if (champ.isSupport) {
			if (item.hasShieldPassive || item.hasHealPassive || item.givesAh) {
				++s;
				reasons.push({ r: "Support-enhancing passive", delta: 1 });
			}
			if (item.isSupportItem) {
				++s;
				reasons.push({ r: "Support gold-generation item", delta: 1 });
			}
		}
		if (champ.isAssassin) {
			if (
				item.givesLethality ||
				item.givesArmorPen ||
				item.hasDashPassive
			) {
				++s;
				reasons.push({ r: "Assassin burst amplified", delta: 1 });
			}
		}
		if (champ.isTank) {
			if (item.givesHp && item.givesArmor) {
				++s;
				reasons.push({
					r: "Dual defensive stats ideal for tank",
					delta: 1,
				});
			}
			if (item.givesAp && !champ.hasApScaling) {
				--s;
				reasons.push({ r: "AP wasted on non-magic tank", delta: -1 });
			}
		}
		if (item.isTrinket) {
			s = 5;
		}
		if (item.isBoots) {
			s = 5;
			if (item.givesMagicPen && !champ.hasApScaling) {
				s -= 2;
				reasons.push({ r: "Magic pen boots wasted", delta: -2 });
			}
			if (item.givesMagicPen && champ.hasApScaling) {
				s += 2;
				reasons.push({ r: "Magic pen boots amplify damage", delta: 2 });
			}
			if (item.givesAs && (champ.isMarksman || champ.hasOnHit)) {
				s += 2;
				reasons.push({
					r: "Attack speed boots suit auto-attackers",
					delta: 2,
				});
			}
			if (item.givesAs && champ.isMage) {
				--s;
				reasons.push({
					r: "Berserker's Greaves wasteful on mage",
					delta: -1,
				});
			}
			if (item.givesLethality && champ.isAssassin) {
				s += 2;
				reasons.push({ r: "Lethality boots suit assassin", delta: 2 });
			}
			if (item.givesLethality && champ.isMage) {
				s -= 2;
				reasons.push({
					r: "Lethality boots wasted on mage",
					delta: -2,
				});
			}
			if (item.givesAh) {
				++s;
				reasons.push({ r: "Haste boots broadly useful", delta: 1 });
			}
		}
		var clamped = Math.max(0, Math.min(10, s)) | 0;
		var tier;
		switch (clamped) {
			case 3:
			case 4:
				tier = forge_data_SynergyTier.Weak;
				break;
			case 5:
			case 6:
				tier = forge_data_SynergyTier.Situational;
				break;
			case 7:
			case 8:
				tier = forge_data_SynergyTier.Good;
				break;
			case 9:
			case 10:
				tier = forge_data_SynergyTier.Core;
				break;
			default:
				tier = forge_data_SynergyTier.Trap;
		}
		reasons.sort(function (a, b) {
			return (Math.abs(b.delta) - Math.abs(a.delta)) | 0;
		});
		var top = reasons.slice(0, 3);
		var result = new Array(top.length);
		var _g = 0;
		var _g1 = top.length;
		while (_g < _g1) {
			var i = _g++;
			result[i] = top[i].r;
		}
		var topReasons = result;
		return {
			itemId: item.id,
			score: clamped,
			tier: tier,
			reasons: topReasons,
		};
	};
	var haxe_iterators_ArrayIterator = function (array) {
		this.current = 0;
		this.array = array;
	};
	haxe_iterators_ArrayIterator.__name__ = true;
	haxe_iterators_ArrayIterator.prototype = {
		hasNext: function () {
			return this.current < this.array.length;
		},
		next: function () {
			return this.array[this.current++];
		},
	};
	var js_Boot = function () {};
	js_Boot.__name__ = true;
	js_Boot.__string_rec = function (o, s) {
		if (o == null) {
			return "null";
		}
		if (s.length >= 5) {
			return "<...>";
		}
		var t = typeof o;
		if (t == "function" && (o.__name__ || o.__ename__)) {
			t = "object";
		}
		switch (t) {
			case "function":
				return "<function>";
			case "object":
				if (o.__enum__) {
					var e = $hxEnums[o.__enum__];
					var con = e.__constructs__[o._hx_index];
					var n = con._hx_name;
					if (con.__params__) {
						s = s + "\t";
						return (
							n +
							"(" +
							(function ($this) {
								var $r;
								var _g = [];
								{
									var _g1 = 0;
									var _g2 = con.__params__;
									while (true) {
										if (!(_g1 < _g2.length)) {
											break;
										}
										var p = _g2[_g1];
										_g1 = _g1 + 1;
										_g.push(js_Boot.__string_rec(o[p], s));
									}
								}
								$r = _g;
								return $r;
							})(this).join(",") +
							")"
						);
					} else {
						return n;
					}
				}
				if (o instanceof Array) {
					var str = "[";
					s += "\t";
					var _g = 0;
					var _g1 = o.length;
					while (_g < _g1) {
						var i = _g++;
						str +=
							(i > 0 ? "," : "") + js_Boot.__string_rec(o[i], s);
					}
					str += "]";
					return str;
				}
				var tostr;
				try {
					tostr = o.toString;
				} catch (_g) {
					return "???";
				}
				if (
					tostr != null &&
					tostr != Object.toString &&
					typeof tostr == "function"
				) {
					var s2 = o.toString();
					if (s2 != "[object Object]") {
						return s2;
					}
				}
				var str = "{\n";
				s += "\t";
				var hasp = o.hasOwnProperty != null;
				var k = null;
				for (k in o) {
					if (hasp && !o.hasOwnProperty(k)) {
						continue;
					}
					if (
						k == "prototype" ||
						k == "__class__" ||
						k == "__super__" ||
						k == "__interfaces__" ||
						k == "__properties__"
					) {
						continue;
					}
					if (str.length != 2) {
						str += ", \n";
					}
					str += s + k + " : " + js_Boot.__string_rec(o[k], s);
				}
				s = s.substring(1);
				str += "\n" + s + "}";
				return str;
			case "string":
				return o;
			default:
				return String(o);
		}
	};
	var tools_DebugSynergy = function () {};
	tools_DebugSynergy.__name__ = true;
	tools_DebugSynergy.main = function () {
		var kayn = {
			id: "Kayn",
			name: "Kayn",
			title: "the Shadow Reaper",
			image: null,
			tags: ["Fighter", "Assassin"],
			partype: "None",
			stats: {
				hp: 655,
				hpperlevel: 90,
				mp: 0,
				mpperlevel: 0,
				movespeed: 340,
				armor: 32,
				armorperlevel: 3.5,
				spellblock: 32,
				spellblockperlevel: 1.25,
				attackrange: 175,
				hpregen: 8,
				hpregenperlevel: 0.8,
				mpregen: 0,
				mpregenperlevel: 0,
				crit: 0,
				critperlevel: 0,
				attackdamage: 68,
				attackdamageperlevel: 4.5,
				attackspeedperlevel: 0.02,
				attackspeed: 0.67,
			},
			passive: null,
			spells: [],
			info: { attack: 6, defense: 4, magic: 2, difficulty: 3 },
			lore: "",
		};
		var champProfile = forge_rules_ProfileBuilder.build(kayn);
		var rift = {
			name: "Riftmaker",
			description:
				"70 Ability Power350 Health15 Ability HasteVoid CorruptionFor each second in combat with enemy champions, deal 2% bonus damage, up to 8%. At maximum strength, gain Omnivamp.",
			image: null,
			gold: { total: 3100, base: 0, sell: 0, purchasable: true },
			tags: [],
			maps: null,
			stats: { FlatMagicDamageMod: 70 },
			from: null,
			into: null,
			depth: 3,
			consumed: false,
			inStore: true,
			hideFromAll: false,
			requiredChampion: null,
			requiredAlly: null,
			effect: null,
			pickRate: 12.0,
		};
		var ardent = {
			name: "Ardent Censer",
			description:
				"When you heal or shield an allied champion, grant them bonus attack speed and on-hit magic damage for a short time.",
			image: null,
			gold: { total: 2500, base: 0, sell: 0, purchasable: true },
			tags: [],
			maps: null,
			stats: { FlatMagicDamageMod: 60 },
			from: null,
			into: null,
			depth: 3,
			consumed: false,
			inStore: true,
			hideFromAll: false,
			requiredChampion: null,
			requiredAlly: null,
			effect: null,
			pickRate: 8.0,
		};
		var riftProfile = forge_rules_ItemClassifier.classify(
			"riftmaker",
			rift,
		);
		var ardentProfile = forge_rules_ItemClassifier.classify(
			"ardent",
			ardent,
		);
		var riftScore = forge_rules_SynergyEngine.score(
			champProfile,
			riftProfile,
		);
		var ardentScore = forge_rules_SynergyEngine.score(
			champProfile,
			ardentProfile,
		);
		console.log(
			"tools/DebugSynergy.hx:80:",
			"Champion: " + champProfile.name,
		);
		console.log(
			"tools/DebugSynergy.hx:81:",
			"Item: " +
				riftProfile.name +
				" => score=" +
				riftScore.score +
				" tier=" +
				Std.string(riftScore.tier) +
				" reasons=" +
				riftScore.reasons.join(", "),
		);
		console.log(
			"tools/DebugSynergy.hx:82:",
			"Item: " +
				ardentProfile.name +
				" => score=" +
				ardentScore.score +
				" tier=" +
				Std.string(ardentScore.tier) +
				" reasons=" +
				ardentScore.reasons.join(", "),
		);
	};
	String.__name__ = true;
	Array.__name__ = true;
	js_Boot.__toStr = {}.toString;
	forge_rules_ItemClassifier.ON_HIT_KW = [
		"on-hit",
		"on hit",
		"applies on-hit",
		"each attack",
		"every attack",
	];
	forge_rules_ItemClassifier.SHIELD_KW = ["shield", "barrier", "absorb"];
	forge_rules_ItemClassifier.HEAL_KW = [
		"heal",
		"restore",
		"regenerat",
		"life steal",
		"lifesteal",
		"omnivamp",
	];
	forge_rules_ItemClassifier.EXECUTE_KW = [
		"execute",
		"below",
		"missing health",
		"threshold",
		"finish",
	];
	forge_rules_ItemClassifier.DOT_KW = [
		"per second",
		"over time",
		"burn",
		"bleed",
		"poison",
	];
	forge_rules_ItemClassifier.SPELLBLADE_KW = [
		"spellblade",
		"after using an ability, your next attack",
	];
	forge_rules_ItemClassifier.SHEEN_KW = [
		"spellblade",
		"sheen",
		"lich bane",
		"trinity force",
		"divine sunderer",
		"iceborn gauntlet",
	];
	forge_rules_ItemClassifier.MANAGATE_KW = [
		"mana charge",
		"mana stack",
		"maximum mana",
		"bonus mana",
		"based on mana",
		"tears",
		"manamune",
		"muramana",
		"archangel",
	];
	forge_rules_ItemClassifier.AOE_KW = [
		"nearby enemies",
		"around you",
		"in an area",
		"surrounding enemies",
		"adjacent enemies",
		"all enemies hit",
	];
	forge_rules_ItemClassifier.DASH_KW = [
		"dash",
		"dashes",
		"leap",
		"leaps",
		"blink",
		"blinks",
		"jump",
		"jumps",
		"charge",
		"charges",
		"fly",
		"flies",
		"vault",
		"roll",
		"rolls",
		"lunge",
		"lunges",
		"dash toward",
		"rapidly move",
	];
	forge_rules_ItemClassifier.ALLY_HEAL_KW = [
		"heal ally",
		"heal allies",
		"when you heal an ally",
		"ally you heal",
		"healed ally",
		"healing an ally",
		"heal a nearby ally",
		"heal an allied",
	];
	forge_rules_ProfileBuilder.ON_HIT_KEYWORDS = [
		"on-hit",
		"on hit",
		"applies on-hit",
		"on each hit",
		"each attack",
		"attacks deal",
		"basic attack",
		"auto attack",
		"attack speed",
		"hits deal",
	];
	forge_rules_ProfileBuilder.AUTO_RESET_KEYWORDS = [
		"resets",
		"reset",
		"cancels",
		"empowered attack",
		"empowered basic",
	];
	forge_rules_ProfileBuilder.DOT_KEYWORDS = [
		"over",
		"seconds",
		"per second",
		"burn",
		"bleed",
		"poison",
		"ignite",
		"damage over time",
		"dot",
	];
	forge_rules_ProfileBuilder.DASH_KEYWORDS = [
		"dash",
		"dashes",
		"leap",
		"leaps",
		"blink",
		"blinks",
		"jump",
		"jumps",
		"charge",
		"charges",
		"fly",
		"flies",
		"vault",
		"roll",
		"rolls",
		"lunge",
		"lunges",
		"dash toward",
		"rapidly move",
	];
	forge_rules_ProfileBuilder.SHIELD_KEYWORDS = [
		"shield",
		"shields",
		"barrier",
		"absorbs damage",
		"damage shield",
	];
	forge_rules_ProfileBuilder.HEAL_KEYWORDS = [
		"heal",
		"heals",
		"restores health",
		"regenerat",
		"lifesteal",
		"life steal",
		"drain",
		"drains life",
	];
	forge_rules_ProfileBuilder.STEALTH_KEYWORDS = [
		"invisible",
		"invisib",
		"stealth",
		"camouflage",
		"unseen",
		"vanish",
	];
	forge_rules_ProfileBuilder.EXECUTE_KEYWORDS = [
		"execute",
		"executes",
		"below",
		"missing health",
		"low health enemies",
		"threshold",
	];
	forge_rules_ProfileBuilder.CC_KEYWORDS = [
		"stun",
		"stuns",
		"root",
		"roots",
		"snare",
		"slow",
		"slow",
		"knock",
		"knockup",
		"knock up",
		"airborne",
		"silence",
		"fear",
		"charm",
		"taunt",
		"suppress",
		"immobilize",
		"bind",
	];
	tools_DebugSynergy.main();
})({});
